import type { SensorDefinition } from "./types";

export const sensorCatalog: SensorDefinition[] = [
  {
    code: "WL-01",
    measurement: "Muka air sawah",
    recommendedType: "Vented hydrostatic level transmitter 0–1 m, IP68",
    signal: "4–20 mA",
    placement: "Tabung AWD pada petak padi representatif",
    role: "Dasar keputusan irigasi padi; membaca muka air di atas dan di bawah permukaan tanah.",
    priority: "Esensial",
  },
  {
    code: "TL-01",
    measurement: "Level tandon",
    recommendedType: "Ultrasonic level sensor IP67, 0,3–8 m",
    signal: "RS485 Modbus / 4–20 mA",
    placement: "Tegak lurus di atas tandon tanpa halangan",
    role: "Menghitung persediaan air dan memicu pengisian pada batas aman.",
    priority: "Esensial",
  },
  {
    code: "FS-01",
    measurement: "Batas tandon",
    recommendedType: "Float switch high/low, normally closed",
    signal: "Digital dry contact",
    placement: "Batas minimum dan maksimum tandon",
    role: "Proteksi independen ketika sensor level atau komunikasi gagal.",
    priority: "Esensial",
  },
  {
    code: "FM-01",
    measurement: "Debit utama",
    recommendedType: "Electromagnetic flow meter IP67",
    signal: "RS485 Modbus + pulse",
    placement: "Pipa lurus setelah pompa",
    role: "Mengukur volume, validasi aliran, dan mendeteksi dry-run atau kebocoran.",
    priority: "Esensial",
  },
  {
    code: "PT-01",
    measurement: "Tekanan discharge",
    recommendedType: "Pressure transmitter 0–10 bar, IP67",
    signal: "4–20 mA",
    placement: "Sesudah pompa, sebelum manifold zona",
    role: "Mendeteksi sumbatan, kebocoran besar, dan operasi pompa tidak normal.",
    priority: "Disarankan",
  },
  {
    code: "SM-01",
    measurement: "Kelembapan tanah",
    recommendedType: "FDR/capacitive multi-depth probe IP68",
    signal: "RS485 Modbus",
    placement: "Zona akar hortikultura atau palawija",
    role: "Dasar keputusan irigasi tanaman lahan kering; bukan sensor utama untuk padi tergenang.",
    priority: "Esensial",
  },
  {
    code: "PH-01",
    measurement: "pH air",
    recommendedType: "Industrial immersion pH probe",
    signal: "RS485 Modbus / 4–20 mA",
    placement: "Flow cell pada jalur sampling",
    role: "Peringatan dini perubahan keasaman; tidak menggantikan uji laboratorium.",
    priority: "Disarankan",
  },
  {
    code: "EC-01",
    measurement: "Konduktivitas air",
    recommendedType: "EC sensor dengan kompensasi suhu",
    signal: "RS485 Modbus / 4–20 mA",
    placement: "Flow cell yang mudah dibersihkan",
    role: "Memantau salinitas dan perubahan konsentrasi ion.",
    priority: "Disarankan",
  },
  {
    code: "TU-01",
    measurement: "Kekeruhan",
    recommendedType: "Optical turbidity sensor 0–1000 NTU",
    signal: "RS485 Modbus",
    placement: "Bypass flow cell dengan aliran stabil",
    role: "Mendeteksi lonjakan sedimen dan risiko penyumbatan.",
    priority: "Opsional",
  },
  {
    code: "EM-01",
    measurement: "Energi pompa dan PLN",
    recommendedType: "Multifunction energy meter + split-core CT",
    signal: "RS485 Modbus",
    placement: "Panel daya setelah MCB",
    role: "Merekam tegangan, arus, daya, faktor daya, dan kWh jaringan.",
    priority: "Esensial",
  },
  {
    code: "PV-01",
    measurement: "Daya PLTS",
    recommendedType: "Register inverter/MPPT atau DC meter + shunt",
    signal: "RS485 Modbus",
    placement: "Panel inverter/MPPT",
    role: "Mengukur produksi surya dan solar fraction tanpa menduplikasi sensor inverter.",
    priority: "Esensial",
  },
  {
    code: "WX-01",
    measurement: "Cuaca mikro",
    recommendedType: "SHT35 + rain gauge; pyranometer opsional",
    signal: "RS485 / SDI-12 / pulse",
    placement: "Tiang 2 m; sensor suhu pembanding di bawah panel",
    role: "Mendukung estimasi kebutuhan air dan evaluasi mikroklimat agrivoltaik.",
    priority: "Opsional",
  },
  {
    code: "MV-01",
    measurement: "Posisi katup zona",
    recommendedType: "Motorized valve dengan limit switch",
    signal: "24 VDC relay + feedback",
    placement: "Manifold setiap zona",
    role: "Membuka aliran per zona dan mengonfirmasi posisi aktual katup.",
    priority: "Aktuator",
  },
];
