import { AlertTriangle, ArrowRight, CheckCircle2, CircleDashed, Database, LockKeyhole } from "lucide-react";
import type { DataSource } from "../domain/types";
import { DataBadge } from "../components/common/DataBadge";
import { PageHeader } from "../components/common/PageHeader";
import { SectionHeading } from "../components/common/SectionHeading";

export type InfoPageKey = "water-quality" | "alerts" | "impact" | "economics" | "sizing" | "scalability" | "deployment" | "study-area" | "methodology" | "references" | "settings";

interface InfoConfig { eyebrow: string; title: string; description: string; source: DataSource; sectionTitle: string; items: Array<{ title: string; body: string; status?: string }>; note: string; }

const pageConfig: Record<InfoPageKey, InfoConfig> = {
  "water-quality": { eyebrow: "OPERATE · WATER QUALITY", title: "Pantau kualitas sebelum menentukan perlakuan", description: "pH, EC, suhu, dan kekeruhan berfungsi sebagai peringatan awal. Pengolahan air hanya dipilih setelah kontaminan dan kebutuhan tanaman dibuktikan.", source: "SIMULATION", sectionTitle: "Parameter pemantauan awal", items: [{ title: "pH · PH-01", body: "Industrial immersion probe pada flow cell; kalibrasi buffer berkala." }, { title: "EC · EC-01", body: "Sensor konduktivitas dengan kompensasi suhu untuk indikasi salinitas." }, { title: "Turbidity · TU-01", body: "Sensor optik untuk lonjakan sedimen dan risiko sumbatan." }], note: "Elektrolisis atau elektrokoagulasi bukan komponen wajib. Pemilihan treatment harus mengikuti hasil uji laboratorium." },
  alerts: { eyebrow: "OPERATE · ALERTS", title: "Peringatan harus menjelaskan tindakan", description: "Setiap alarm menggabungkan tingkat risiko, bukti sensor, konsekuensi, dan respons yang disarankan.", source: "SIMULATION", sectionTitle: "Klasifikasi alarm", items: [{ title: "Warning", body: "Operasi masih dapat berlangsung dengan pengawasan atau penyesuaian." }, { title: "Critical", body: "Peralatan dihentikan oleh interlock atau membutuhkan inspeksi segera." }, { title: "Offline", body: "Data tidak boleh dipakai untuk keputusan otomatis sampai koneksi pulih." }], note: "Riwayat acknowledge, penanggung jawab, dan waktu penyelesaian membutuhkan backend pada fase IoT." },
  impact: { eyebrow: "ANALYZE · ENVIRONMENTAL IMPACT", title: "Ukur dampak tanpa melebihkan klaim", description: "Dampak dinilai dari emisi energi, penggunaan air, mikroklimat, produktivitas lahan, dan akhir masa pakai komponen.", source: "PROJECTED", sectionTitle: "Batas analisis dampak", items: [{ title: "Carbon emission", body: "Bandingkan diesel, listrik jaringan, dan bauran solar-grid dengan faktor emisi tervalidasi." }, { title: "Water efficiency", body: "Ukur volume per hektare dan per kilogram hasil, bukan hanya durasi pompa." }, { title: "Land & circularity", body: "Nilai land equivalent ratio serta rencana panel, kabel, sensor, dan elektronik di akhir umur." }], note: "Naungan parsial dapat menurunkan suhu mikro dan evaporasi, tetapi dampak hasil tanaman harus diverifikasi terhadap petak kontrol." },
  economics: { eyebrow: "ANALYZE · ECONOMIC ANALYSIS", title: "Bandingkan biaya sepanjang umur sistem", description: "Investasi awal tidak cukup untuk menyimpulkan pilihan termurah. Analisis harus memasukkan energi, perawatan, penggantian, dan nilai waktu uang.", source: "PROJECTED", sectionTitle: "Empat skenario pembanding", items: [{ title: "Diesel", body: "CAPEX pompa, bahan bakar, transportasi, oli, dan perawatan mesin." }, { title: "PLN", body: "Biaya sambungan, tarif, konsumsi kWh, dan reliabilitas jaringan." }, { title: "PLTS + baterai besar", body: "Investasi dan penggantian baterai menjadi komponen biaya utama." }, { title: "PLTS + PLN + tandon", body: "Tandon menggantikan kebutuhan baterai pompa besar dan PLN menjaga keandalan." }], note: "Output yang dibutuhkan: CAPEX, OPEX, biaya air per m³, NPV/LCOE, payback period, dan sensitivitas harga energi." },
  sizing: { eyebrow: "PLAN · SYSTEM SIZING", title: "Ukuran sistem mengikuti kebutuhan air", description: "Kapasitas final tidak ditentukan dari contoh gambar, tetapi dari kebutuhan tanaman, debit sumber, total head, jam pompa efektif, dan kehilangan jaringan.", source: "PROJECTED", sectionTitle: "Urutan sizing", items: [{ title: "1 · Water demand", body: "Hitung ETc, hujan efektif, efisiensi irigasi, luas, dan pola tanam." }, { title: "2 · Hydraulic duty", body: "Tentukan debit desain, total dynamic head, diameter pipa, dan efisiensi pompa." }, { title: "3 · Energy & storage", body: "Hitung daya pompa, profil PLTS, kapasitas tandon, dan kebutuhan grid assist." }], note: "Semua angka kapasitas tetap DATA_REQUIRED sampai survei lapangan dan skenario operasi disepakati." },
  scalability: { eyebrow: "PLAN · SCALABILITY", title: "Arsitektur yang sama, kapasitas yang berbeda", description: "Modul pompa, tandon, zona, gateway, dan dashboard dapat ditambah tanpa mengubah prinsip solar-first dan penyimpanan air.", source: "PROJECTED", sectionTitle: "Tiga skala awal", items: [{ title: "Kecil · ±1 ha", body: "3–4 petani; satu pompa, tandon, RTU, serta sensor air dan energi esensial." }, { title: "Menengah · ±5 ha", body: "Kelompok tani/P3A; beberapa zona, node LoRa, dan operasi bersama." }, { title: "Besar · ±20 ha", body: "Gapoktan/BUMDes; jaringan terpusat, multi-pompa, dan dashboard berbasis peran." }], note: "Luasan adalah skenario komunikasi gagasan, bukan batas teknis atau spesifikasi final." },
  deployment: { eyebrow: "PLAN · DEPLOYMENT", title: "Pilot satu musim sebelum replikasi", description: "Implementasi memerlukan baseline, commissioning, pengukuran satu musim, dan keputusan go/no-go berbasis indikator.", source: "PROJECTED", sectionTitle: "Roadmap implementasi", items: [{ title: "01 · Prepare", body: "Survei sumber, head, lahan, pola tanam, jaringan, pengelola, dan baseline biaya." }, { title: "02 · Pilot", body: "Bangun ±1 ha, kalibrasi sensor, latih operator, dan ukur satu musim." }, { title: "03 · Evaluate & scale", body: "Bandingkan air, energi, hasil, biaya, mikroklimat, dan penerimaan petani." }], note: "PLN, pemerintah desa/kecamatan, kelompok tani/P3A, BUMDes, kampus, dan penyedia teknologi memiliki peran berbeda." },
  "study-area": { eyebrow: "RESEARCH · STUDY AREA", title: "Kecamatan Pringgarata sebagai ruang lingkup", description: "Identitas studi adalah Kecamatan Pringgarata, Kabupaten Lombok Tengah, Nusa Tenggara Barat. Lokasi pilot spesifik ditentukan melalui survei.", source: "RESEARCH", sectionTitle: "Data lokasi yang harus dikunci", items: [{ title: "Water", body: "Sumber, debit musiman, kualitas, elevasi, dan akses distribusi." }, { title: "Agriculture", body: "Komoditas, kalender tanam, luasan, praktik irigasi, dan kelompok pengelola." }, { title: "Energy", body: "Iradiasi, profil beban, kondisi jaringan PLN, penggunaan diesel, dan tarif." }], note: "Jangan menggunakan Desa Sisik sebagai identitas utama sistem. Gunakan Pringgarata Pilot System atau Pilot Unit 01." },
  methodology: { eyebrow: "RESEARCH · METHODOLOGY", title: "Dari literatur menuju asumsi yang dapat diuji", description: "Metode memisahkan data sekunder, asumsi desain, keluaran simulasi, dan hasil pengukuran pilot.", source: "RESEARCH", sectionTitle: "Alur analisis", items: [{ title: "Evidence", body: "Kumpulkan data resmi, paper, standar, dan wawancara; catat sumber dan batasnya." }, { title: "Model", body: "Bangun skenario air–hidraulik–energi–ekonomi–lingkungan dengan unit konsisten." }, { title: "Validation", body: "Uji terhadap baseline dan petak kontrol; laporkan ketidakpastian dan sensitivitas." }], note: "Hasil simulasi tidak disebut results eksperimen. Gunakan istilah analisis kelayakan dan dampak gagasan." },
  references: { eyebrow: "RESEARCH · REFERENCES", title: "Pusat bukti dan keterlacakan asumsi", description: "Modul referensi akan menyimpan sitasi, variabel yang didukung, lokasi studi, metode, dan keterbatasan setiap sumber.", source: "RESEARCH", sectionTitle: "Literature integration matrix", items: [{ title: "Claim", body: "Pernyataan apa dalam esai yang didukung sumber ini?" }, { title: "Evidence", body: "Data, metode, satuan, lokasi, dan tahun apa yang dapat digunakan?" }, { title: "Integration", body: "Apakah sumber memperkuat, membatasi, atau membandingkan gagasan PRINGGASURYA?" }], note: "Daftar pustaka tervalidasi akan ditambahkan pada fase research content; jangan menampilkan sitasi yang belum diperiksa." },
  settings: { eyebrow: "SYSTEM · SETTINGS", title: "Konfigurasi prototipe", description: "Pengaturan fase ini hanya menjelaskan kesiapan integrasi. Live mode tetap terkunci sampai backend dan autentikasi tersedia.", source: "SIMULATION", sectionTitle: "Environment readiness", items: [{ title: "Data source", body: "SIMULATION aktif. LIVE SYSTEM NOT CONFIGURED." }, { title: "API & stream", body: "Endpoint belum diisi; frontend tidak terhubung langsung ke MQTT." }, { title: "Command security", body: "Authentication, authorization, confirmation, acknowledgment, dan audit log belum dikonfigurasi." }], note: "Tidak ada credential MQTT, database, atau perangkat yang disimpan di frontend maupun repository." },
};

export function InfoPage({ page }: { page: InfoPageKey }) {
  const config = pageConfig[page];
  return (
    <>
      <PageHeader eyebrow={config.eyebrow} title={config.title} description={config.description} source={config.source} />
      <section className="info-lead"><div><DataBadge source={config.source} /><h2>{config.sectionTitle}</h2></div><p>Modul ini sudah memiliki struktur konten dan akan memperoleh kalkulasi atau koneksi data pada fase pengembangan berikutnya.</p></section>
      <section className="info-card-grid">{config.items.map((item, index) => <article key={item.title}><span>0{index + 1}</span><h3>{item.title}</h3><p>{item.body}</p>{item.status && <small>{item.status}</small>}</article>)}</section>
      <section className="readiness-panel"><div><CircleDashed /><span><b>Phase-ready module</b><p>{config.note}</p></span></div><div className="readiness-steps"><span><CheckCircle2 /> Information architecture</span><span><CheckCircle2 /> Responsive shell</span><span><Database /> Data integration pending</span><span><LockKeyhole /> Secure controls pending</span></div></section>
      <section className="next-phase-note"><AlertTriangle /><p><b>Batas fase:</b> halaman ini tidak menyajikan data nyata atau hasil eksperimen. Setiap nilai final harus memiliki sumber, waktu, satuan, serta status LIVE, HISTORICAL, RESEARCH, SIMULATION, atau PROJECTED.</p><ArrowRight /></section>
    </>
  );
}
